package.json
src/app/(protected)/member/estimate-pending/_components/EstimateSubHeader.tsx
src/app/(protected)/member/estimate-pending/_components/PendingCard.tsx
src/app/(protected)/member/estimate-pending/page.tsx
tailwind.config.mjs

chip과 button 컴포넌트 연결까지 ui 완성
header와 tab 완성된 후에 연결 예정

[김다은] 대기중인 견적 페이지 ui 완성

---

src/app/(protected)/member/estimate-past/_components/EstimateDetail.tsx
src/app/(protected)/member/estimate-past/_components/ReceivedEstimate.tsx
src/app/(protected)/member/estimate-past/page.tsx
src/app/common/page.tsx
src/components/title/Title.tsx
src/components/title/TitleData.ts

받았던 견적 페이지 - 1차 작업 완료, 추후에 디테일 조금 더 수정 예정
title - chip 연결, 반응형에 따른 일부 수정

[김다은] 받았던 견적 페이지 ui & title 수정

---

src/components/DevNav.tsx

- DevNav에 게스트, 컴포넌트 관련 라우트 추가했습니다.

feat: 게스트, 컴포넌트 관련 라우트 추가

---

src/app/(protected)/member/estimate-pending/_components/PendingCard.tsx

PendingCard에서 발생한 Button의 round 프룹스 제거 

[김다은] 배포 에러 해결

---

src/app/landing/layout.tsx
src/app/landing/page.tsx
src/app/layout.tsx
src/app/review/page.tsx
src/components/layout/Gnb.tsx
src/components/list/GnbList.tsx
src/constant/constant.ts

- 모든 페이지에서 gnb를 확인할 수 있도록 반영했습니다.

[UI] 전체 layout에 gnb 적용

---

package-lock.json
package.json
src/app/(protected)/customer/estimate-request/DesktopEstimateForm.tsx
src/app/(protected)/customer/estimate-request/MobileEstimateForm.tsx
src/app/(protected)/customer/estimate-request/_components/AddressCardModal.tsx
src/app/(protected)/customer/estimate-request/_components/DaumPostcodeModal.tsx
src/types/Address.ts

- react-daum-postcode 라이브러리 설치
- DaumPostcodeModal.tsx 컴포넌트 추가 및 커스텀 디자인 적용
- 주소 타입 정의(Address.ts) 추가
- 주소 검색 결과를 선택하여 AddressCardModal과 연동 처리
- 상세 주소를 어디서 받을지 고민 중입니다..

feat: 카카오 우편번호 검색 기능 구현 및 모달 UI 연동

---

package-lock.json
package.json
src/app/review/component/Main.tsx
src/app/review/component/ReviewCost.tsx
src/app/review/component/Reviews.tsx
src/app/review/component/ReviewsInner.tsx
src/app/review/page.tsx
src/hooks/useMediaHook.ts

feat:작성가능한 리뷰 반응형 UI

---

src/app/(protected)/customer/my-estimates/_components/EstimateDetailInfo.tsx
src/app/(protected)/customer/my-estimates/estimate-past/[id]/PastDetail.tsx
src/app/(protected)/customer/my-estimates/estimate-pending/[id]/PendingDetail.tsx
src/app/(protected)/customer/my-estimates/favorite-drivers/FavoriteDrivers.tsx
src/components/card/DriverFindCard.tsx
src/constant/driverType.ts

- 상세 페이지 반응형 수정도 완료되어 이제 내 견적관리 + 찜한 기사님 페이지 ui는 작업 다 완료했습니다.

[김다은] 상세 페이지 반응형 ui + 찜한 기사님 체크박스 수정

---

src/components/dropdown/NotificationDropdown.tsx
src/components/dropdown/ProfileDropdown.tsx
src/constant/constant.ts

- 프로필 드롭다운 레이어가 userType에 따라 분기처리 되도록 수정
- 알림 관련 bug fix

프로필 userType에 따라 분기처리, route 수정

---

src/components/dropdown/ProfileDropdown.tsx
src/constant/constant.ts

- GNB 중 연결되지 않는 부분이 있어 수정했습니다.

fix: route 수정

---

src/constant/constant.ts

- 기사님으로 로그인 했을 경우 드롭다운 메뉴에 마이페이지와 로그아웃만 노출되도록 수정했습니다.

기사님/프로필 드롭다운 메뉴 수정

---

src/app/(protected)/driver/my-estimates/sent/[id]/page.tsx
src/app/(protected)/driver/my-estimates/sent/_components/CompletedEstimateCard.tsx
src/app/(protected)/driver/my-estimates/sent/_components/CustomerEstimateCard.tsx
src/app/(protected)/driver/my-estimates/sent/_components/EstimateCardList.tsx
src/app/(protected)/driver/my-estimates/sent/page.tsx
src/app/(protected)/driver/received-requests/_components/InputPrice.tsx
src/app/(protected)/driver/received-requests/_components/ReceivedRequestCard.tsx
src/app/(protected)/driver/received-requests/_components/RejectEstimateModal.tsx
src/app/(protected)/driver/received-requests/_components/RequestCardList.tsx
src/app/(protected)/driver/received-requests/_components/SendEstimateModal.tsx
src/app/(protected)/driver/received-requests/page.tsx
src/components/common/EstimateDetailInfo.tsx
src/components/filter/FilterToggleButton.tsx

- 모달 반응형 스타일 적용
- 주요 페이지 반응형 대응
- 받은요청 페이지
- 보낸견적조회 페이지
- 견적상세 페이지

[스타일] 주요 페이지 및 모달 반응형 스타일 적용

---

src/app/(protected)/customer/my-estimates/estimate-pending/PendingEstimates.tsx
src/app/(protected)/customer/my-estimates/estimate-pending/_components/PendingCard.tsx
src/lib/api/api-myEstimate.ts
src/types/estimateType.ts
src/utills/addressUtils.ts
src/utills/moveUtils.ts

대기 중인 견적 리스트 api 연동
견적 요청 폼 작성 후 견적 요청 건 정보가 보이는 지만 일단 확인 예정 

[김다은] 대기 중인 견적 리스트 api 연동

---

src/app/[locale]/(auth)/login/customer/page.tsx
src/app/[locale]/(auth)/login/driver/page.tsx
src/app/[locale]/(auth)/signup/customer/page.tsx
src/app/[locale]/(auth)/signup/driver/page.tsx

1. 로그인 회원가입 페이지 소셜로그인 이미지에 링크추가

[Feat 이지수] 소셜 로그인 구현 완료

---

src/app/[locale]/(protected)/customer/estimate-request/DesktopEstimateForm.tsx
src/app/[locale]/(protected)/customer/estimate-request/MobileEstimateForm.tsx
src/app/[locale]/(protected)/customer/estimate-request/_components/card/MoveTypeCard.tsx
src/app/[locale]/(protected)/customer/estimate-request/_components/modal/AddressCardModal.tsx
src/constant/moveTypes.ts
src/i18n/request.ts
src/messages/en/EstimateReq.json
src/messages/ko/EstimateReq.json
src/messages/ko/Landing.json
src/messages/zh/EstimateReq.json

feat:견적요청 다국어

---

src/app/[locale]/(guest)/drivers/_components/Filters.tsx
src/app/[locale]/(guest)/drivers/_components/FindDrivers.tsx
src/app/[locale]/(guest)/drivers/_components/LikedDrivers.tsx
src/app/[locale]/(protected)/customer/my-estimates/estimate-past/PastEstimates.tsx
src/app/[locale]/(protected)/driver/received-requests/page.tsx
src/app/[locale]/common/page.tsx
src/components/dropdown/FilterDropdown.tsx
src/components/dropdown/SortDropdown.tsx
src/i18n/request.ts
src/messages/en/FindDriver.json
src/messages/ko/FindDriver.json
src/messages/zh/FindDriver.json

- 기사님 찾기 다국어 변경 했습니다.
- Sort랑 Filter prop추가

feat: 기사님 찾기 다국어

---

src/app/[locale]/(guest)/drivers/[id]/_components/DesignatedEstimateButton.tsx
src/app/[locale]/(guest)/drivers/[id]/_components/DriverInfo.tsx
src/app/[locale]/(guest)/drivers/[id]/_components/EstimateRequestModal.tsx
src/app/[locale]/(guest)/drivers/[id]/_components/FavoriteButton.tsx
src/app/[locale]/(guest)/drivers/[id]/_components/RequestEstimate.tsx
src/app/[locale]/(guest)/drivers/[id]/page.tsx
src/app/[locale]/(guest)/drivers/page.tsx
src/components/Service.tsx
src/components/card/DriverFindCard.tsx
src/components/driver/DriverReviews.tsx
src/components/driver/DriverSimpleInfo.tsx
src/messages/en/FindDriver.json
src/messages/ko/FindDriver.json
src/messages/zh/FindDriver.json

feat: 기사님 상세 다국어

---

src/app/[locale]/(protected)/driver/my-page-edit/page.tsx
src/app/[locale]/(protected)/driver/my-page/_components/EditButtons.tsx
src/lib/api/api-profile.ts

1. 기사님 기본 정보 수정 페이지 UI 완성하고 API 연결했습니다.
- 부족한 점이 있을 수 있어서 보시고 리팩터링 필요하면 해주세요! 

[FEAT] 기사님 기본정보 수정 페이지 UI 및 API 연결

---

src/app/[locale]/(protected)/driver/received-requests/page.tsx
src/app/[locale]/common/page.tsx
src/components/chip/ChipCircle.tsx
src/components/filter/FilterModal.tsx
src/components/filter/FilterSection.tsx
src/lib/api/api-driver.ts
src/types/request.ts
src/utills/RequestMapper.tsx

[기능] 받은요청 페이지 프론트/백 연동

---

src/app/[locale]/(protected)/customer/estimate-request/DisabledForm.tsx
src/app/[locale]/(protected)/customer/my-estimates/estimate-past/PastEstimates.tsx
src/app/[locale]/(protected)/customer/my-estimates/estimate-past/[id]/PastDetail.tsx
src/app/[locale]/(protected)/customer/my-estimates/estimate-past/_components/EstimateDetail.tsx
src/app/[locale]/(protected)/customer/my-estimates/estimate-past/_components/ReceivedEstimate.tsx
src/app/[locale]/(protected)/customer/my-estimates/estimate-pending/PendingEstimates.tsx
src/app/[locale]/(protected)/customer/my-estimates/estimate-pending/[id]/PendingDetail.tsx
src/app/[locale]/(protected)/customer/my-estimates/estimate-pending/_components/EstimateSubHeader.tsx
src/app/[locale]/(protected)/customer/my-estimates/estimate-pending/_components/PendingCard.tsx
src/components/Title.tsx
src/components/chip/ChipConfirmed.tsx
src/components/chip/EstimateStatus.tsx
src/lib/api/api-myEstimate.ts
src/middleware.ts
src/types/estimateType.ts
src/utills/addressUtils.ts

내 견적관리 api 모두 연동 + 테스트 완료
찜한 기사님 관련 부분 오늘 밤 안으로 모두 연결하겠습니다.

[김다은] 내 견적관리 api 모두 연동 + 테스트 완

---

src/app/[locale]/(protected)/customer/my-estimates/estimate-past/PastEstimates.tsx
src/app/[locale]/(protected)/customer/my-estimates/estimate-past/_components/ReceivedEstimate.tsx
src/app/[locale]/(protected)/driver/my-page/_components/EditButtons.tsx
src/app/[locale]/(protected)/driver/my-page/page.tsx
src/app/[locale]/(protected)/driver/received-requests/_components/ReceivedRequestCard.tsx
src/app/[locale]/(protected)/driver/received-requests/page.tsx
src/components/filter/FilterModal.tsx
src/i18n/request.ts
src/messages/en/DriverMypage.json
src/messages/en/ReceivedReq.json
src/messages/ko/DriverMypage.json
src/messages/ko/ReceivedReq.json
src/messages/zh/DriverMypage.json
src/messages/zh/ReceivedReq.json

Feat: 다국어 기사님 마이페이지, 받은 견적

---

src/app/[locale]/(protected)/driver/my-estimates/rejected/_components/CompletedRejectedCard.tsx
src/app/[locale]/(protected)/driver/my-estimates/rejected/_components/RejectedEstimateCard.tsx
src/app/[locale]/(protected)/driver/my-estimates/sent/[id]/page.tsx
src/app/[locale]/(protected)/driver/my-estimates/sent/_components/CompletedEstimateCard.tsx
src/app/[locale]/(protected)/driver/my-estimates/sent/_components/CustomerEstimateCard.tsx
src/app/[locale]/(protected)/driver/received-requests/_components/RejectEstimateModal.tsx
src/app/[locale]/(protected)/driver/received-requests/_components/SendEstimateModal.tsx
src/components/chip/ChipConfirmed.tsx
src/components/common/EstimateDetailInfo.tsx
src/i18n/request.ts
src/messages/en/MyEstimate.json
src/messages/en/ReceivedReq.json
src/messages/ko/MyEstimate.json
src/messages/ko/ReceivedReq.json
src/messages/zh/MyEstimate.json
src/messages/zh/ReceivedReq.json

- 기사님 마이페이지, 받은 요청, 내 견적 다국어 변환 했습니다.

locale: 기사님 마이페이지, 받은요청, 내 견적 다국어

---

package-lock.json
package.json
src/app/[locale]/layout.tsx
src/components/container/ConditionalTransitionWrapper.tsx
src/components/container/PageTransitionWrapper.tsx
src/components/dropdown/ProfileDropdown.tsx
src/components/gnb/Gnb.tsx
src/components/gnb/GnbMenuList.tsx
src/components/gnb/_components/Logo.tsx
src/hooks/useTransitionRouter.ts

- 페이지 전환할 때 useTransiton을 활용해 끊기는 느낌을 최소한으로 느끼도록 적용했습니다.
- 현재는 GNB에만 적용되어 있고 추 후 useRouter()를 useTransitionRouter()로 변경해야 합니다.

[FE] 페이지 이동 시 useTrasitionRouter 적용

---

src/app/[locale]/(protected)/driver/my-estimates/rejected/_components/CompletedRejectedCard.tsx
src/app/[locale]/(protected)/driver/my-estimates/rejected/_components/RejectedCardList.tsx
src/app/[locale]/(protected)/driver/my-estimates/rejected/_components/RejectedEstimateCard.tsx
src/app/[locale]/(protected)/driver/my-estimates/rejected/page.tsx
src/app/[locale]/(protected)/driver/my-estimates/sent/[id]/page.tsx
src/app/[locale]/(protected)/driver/my-estimates/sent/_components/CompletedEstimateCard.tsx
src/app/[locale]/(protected)/driver/my-estimates/sent/_components/CustomerEstimateCard.tsx
src/lib/api/api-driver.ts
src/messages/ko/MyEstimate.json
src/types/estimateType.ts
src/utills/RequestMapper.tsx
src/utills/dateUtils.tsx

- 반려요청 페이지 API 연동  
- 견적상세 페이지 API 연동 

[기능] 반려요청 페이지 및 견적상세 페이지 API 연동

---

src/app/[locale]/(guest)/drivers/[id]/_components/DesignatedEstimateButton.tsx
src/app/[locale]/(guest)/drivers/[id]/_components/Toast.tsx
src/app/[locale]/(guest)/drivers/_components/FindDrivers.tsx
src/components/card/DriverFindCard.tsx
src/messages/en/FindDriver.json
src/messages/ko/FindDriver.json
src/messages/zh/FindDriver.json

1. 토스트 모달 뜰때 스크롤해도 위치 고정되게 변경했습니다
2. 지정견적요청시 로딩 추가했습니다
3. 기사님 찾기에서 검색 시 엔터 후 검색되게 변경했습니다.
- 추가로 이미지가 정해진 사이즈에서 벗어나는 문제를 해결해볼려 했는데 이게 잘 될 때도 있고 안될때도 있어서 어디 문제인지 모르겠습니다..
- 기사님 찾기에서 마지막까지 스크롤 할 때 쯤에 key={driver.id} 로 했는데 키가 중복되는 에러가 뜨는데 왜 뜨는지 모르겠어서 다 하고 한번 seed를 초기화해도 같은 문제가 뜨는지 확인해봐야 할 것 같습니다

[FIX] 토스트모달, 검색 오류 해결, 지정 견적요청 로딩추가

---

src/app/[locale]/(protected)/customer/review/_components/ModalContent.tsx
src/app/[locale]/(protected)/customer/review/_components/MyReviews.tsx
src/app/[locale]/(protected)/customer/review/_components/ReviewCost.tsx
src/app/[locale]/(protected)/customer/review/_components/ReviewModal.tsx
src/app/[locale]/(protected)/customer/review/_components/ReviewsInner.tsx
src/app/[locale]/(protected)/customer/review/_components/WritableReviews.tsx
src/components/notification/NotificationDropdown.tsx
src/lib/api/api-review.ts

- 리뷰 페이지네이션 연동
- 칩 컴포넌트 연동
- 리액트 쿼리 적용
- notification에러때문에 주석처리 한줄한거 있습니다.

Feat:리뷰 페이지네이션 연동, 컴포넌트 연동, 리액트 쿼리 적용

---

src/app/[locale]/(guest)/drivers/[id]/_components/DesignatedEstimateButton.tsx

1. 지정견적 요청 버튼 클릭시 바로 UI가 새로고침해야 반영이 되었는데 바로 반영 될 수 있도록 수정했습니다

[FIX] 지정견적요청 완료 바로 반영

---

src/app/[locale]/layout.tsx
src/components/common-modal/ToastModal.tsx

토스트 모달 오류 수정 완료했습니다
혹시 색상이나 디자인 의견 추가로 있으시면 말씀해주시면 감사하겠습니다

[김다은] 토스트 모달 오류 수정

---

src/app/[locale]/(guest)/drivers/[id]/_components/Toast.tsx
src/app/[locale]/(protected)/customer/review/_components/MyReviews.tsx
src/app/[locale]/(protected)/customer/review/_components/ReviewModal.tsx
src/app/[locale]/(protected)/customer/review/_components/WritableReviews.tsx

Feat:lottie 오류 수정

---

src/app/[locale]/(protected)/customer/my-estimates/estimate-pending/[id]/PendingDetail.tsx
src/app/[locale]/(protected)/customer/my-estimates/estimate-pending/_components/PendingCard.tsx
src/components/common/EstimateDetailInfo.tsx
src/messages/en/MyEstimates.json
src/messages/ko/MyEstimates.json

다국어 기능 추가 & 상세페이지 에러 해결
- 다국어는 추후 계속 추가할 예정입니다!

[김다은] 다국어 기능 추가 & 상세페이지 에러 해결

---

src/app/[locale]/(guest)/drivers/[id]/page.tsx
src/app/[locale]/(protected)/customer/my-estimates/favorite-drivers/FavoriteDrivers.tsx
src/app/[locale]/layout.tsx
src/app/[locale]/toast/page.tsx
src/components/ShareDriver.tsx
src/components/common-modal/ToastModal.tsx
tsconfig.json

토스트 모달 위치 수정 & 카카오톡 공유 기능
- 기사님 찾기에서 해당 기사님 공유하는 기능 추가했습니다!
- 이후에 견적서 공유하는 기능도 추가해 놓도록 하겠습니다!

[김다은] 토스트 모달 위치 수정 & 카카오톡 공유 기능

---

src/app/[locale]/(protected)/customer/review/_components/MyReviews.tsx
src/app/[locale]/(protected)/customer/review/_components/WritableReviews.tsx
src/app/[locale]/(protected)/customer/review/page.tsx
src/i18n/request.ts
src/types/reviewType.ts
src/utills/batchTranslate.ts

- 다국어 전용 컴포 따로 빼고 불러올때 SEOUL로 먼저뜨고 한국어로 바뀌는 오류 등 수정했습니다.

Locale: my review

---

src/app/[locale]/(protected)/customer/my-estimates/estimate-past/[id]/PastDetail.tsx
src/app/[locale]/(protected)/customer/my-estimates/estimate-pending/[id]/PendingDetail.tsx
src/app/[locale]/(protected)/driver/my-estimates/sent/[id]/page.tsx

카카오톡 견적서 공유하기 기능 추가
- 페이스북도 이어서 작업할 예정입니다. 

[김다은] 카카오톡 견적서 공유하기 기능 추가

---

src/app/[locale]/(guest)/drivers/[id]/page.tsx
src/app/[locale]/(protected)/customer/my-estimates/estimate-past/[id]/PastDetail.tsx
src/app/[locale]/(protected)/customer/my-estimates/estimate-pending/[id]/PendingDetail.tsx
src/app/[locale]/(protected)/driver/my-estimates/sent/[id]/page.tsx
src/hooks/useKakaoShare.ts

[김다은] 카카오톡 견적서 공유하기 오류 수정

---

src/lib/FetchClient.ts

로그아웃 삭제 모듈 clearAccessToken 변경

[fix 이지수]로그아웃 삭제 모듈 clearAccessToken 변경

---

src/app/[locale]/(guest)/drivers/[id]/_components/DriverInfo.tsx
src/app/[locale]/(protected)/driver/my-estimates/sent/page.tsx
src/app/[locale]/(protected)/driver/received-requests/_components/ReceivedRequestCard.tsx
src/components/card/DriverFindCard.tsx

Locale: driver 찾기, 받은견적

---

src/app/[locale]/(protected)/driver/my-estimates/sent/[id]/page.tsx
src/app/[locale]/(protected)/driver/received-requests/_components/ReceivedRequestCard.tsx

- 받은 견적요청의 request.createAt에 DeepL 적용했습니다.

[황수정] 기사님 / 받은 견적요청 request.createdAt DeepL 적용

---

src/app/[locale]/(protected)/customer/my-estimates/estimate-past/_components/EstimateDetail.tsx
src/app/[locale]/(protected)/customer/my-estimates/estimate-pending/[id]/PendingDetail.tsx
src/app/[locale]/(protected)/customer/review/_components/ModalContent.tsx
src/app/[locale]/(protected)/customer/review/_components/MyReviews.tsx
src/app/[locale]/(protected)/customer/review/_components/ReviewCost.tsx
src/app/[locale]/(protected)/customer/review/_components/ReviewsInner.tsx
src/app/[locale]/(protected)/customer/review/_components/WritableReviews.tsx
src/app/[locale]/(protected)/driver/my-estimates/rejected/_components/CompletedRejectedCard.tsx
src/app/[locale]/(protected)/driver/my-estimates/sent/_components/CompletedEstimateCard.tsx
src/app/[locale]/(protected)/driver/my-estimates/sent/_components/CustomerEstimateCard.tsx
src/app/[locale]/(protected)/driver/received-requests/_components/InputPrice.tsx
src/app/[locale]/(protected)/driver/received-requests/_components/RejectEstimateModal.tsx
src/app/[locale]/(protected)/driver/received-requests/_components/SendEstimateModal.tsx
src/components/card/DriverFindCard.tsx
src/components/common/EstimateDetailInfo.tsx
src/messages/en/Common.json
src/messages/ko/Common.json
src/messages/zh/Common.json

-리뷰 동적 다국어 덜 된 부분 넣었습니다.
-리뷰 내용 동적으로 가져올 때 en, zh끊겨서 나오는 오류 있는데 deepL API 오류 가능성 있어서 내일 다시 점검합니다.

Locale: review 동적 다국어

---

src/app/[locale]/(auth)/login/customer/page.tsx
src/app/[locale]/(auth)/login/driver/page.tsx
src/components/profile/DriverProfileForm.tsx
src/hooks/useAuthForm.ts
src/lib/FetchClient.ts
src/messages/en/Login.json
src/messages/ko/DriverProfileEdit.json
src/messages/ko/Login.json
src/messages/zh/Login.json
src/utills/getCookieDomain.ts

1. 로그인 및 프로필 페이지 토스트모달 반영
2. 로컬 토큰생성시 도메인값 하드코딩된 부분 .env로 변경

[fix 이지수 ]로그인 및 프로필 페이지 토스트모달 반영 및 토큰 도메인 설정값 .env로 변경

---

src/app/[locale]/(auth)/signup/customer/page.tsx
src/app/[locale]/(auth)/signup/driver/page.tsx
src/app/[locale]/(protected)/driver/my-page-edit/page.tsx
src/app/[locale]/layout.tsx
src/components/WelcomeToastTrigger.tsx
src/hooks/useAuthForm.ts
src/middleware.ts

1. 소셜로그인 토스트 모달 추가
2. 미들웨어 토큰 요청 로직 추가
3. name 유효성 검사 제거

[Fix/middleware 이지수] 소셜로그인 토스트 모달 추가 및 미들웨어 토큰 요청 로직 추가 및 name 유효성 검사 제거

---

src/app/[locale]/landing/_component/ChangeImages.tsx
src/components/Button.tsx
src/components/gnb/Gnb.tsx

- 로그인 버튼 높이값 조정했습니다. 
- 랜딩페이지 텍스트가 레이아웃에서 벗어나는 현상이 있어 수정했습니다.

[황수정] 로그인버튼, 랜딩페이지 텍스트 포지션 조정

---

src/app/[locale]/(protected)/customer/review/_components/ReviewModal.tsx
src/app/[locale]/(protected)/driver/received-requests/_components/SendEstimateModal.tsx
src/components/InputText.tsx

Style: modal error revise

---

src/messages/en/DriverProfileEdit.json
src/messages/zh/DriverProfileEdit.json

[fix: 이지수] 프로필 생성 토스트 다국어 모달 수정

---

src/app/[locale]/estimate/shared/[token]/page.tsx
src/components/gnb/Gnb.tsx

견적서 공유용 페이지 수정 
- 데이터 렌더링이 조금 걸려서인지 처음에 값이 없다고 인식해서 튕겨나가는 현상이 있어 해결했습니다. 

[김다은] 견적서 공유용 페이지 데이터 연결 수정

---

src/app/[locale]/estimate/shared/[token]/page.tsx
src/messages/zh/MyEstimate.json
src/messages/zh/MyEstimates.json

다국어 중국어 추가 & 견적서 공유용 페이지 디자인 수정

[김다은] 다국어 중국어 추가 & 견적서 공유용 페이지 디자인 수정

---

src/app/[locale]/(protected)/driver/my-estimates/rejected/_components/CompletedRejectedCard.tsx
src/app/[locale]/(protected)/driver/my-estimates/sent/_components/AddressDateSection.tsx
src/app/[locale]/(protected)/driver/my-estimates/sent/_components/CompletedEstimateCard.tsx
src/app/[locale]/(protected)/driver/my-estimates/sent/_components/CustomerEstimateCard.tsx

[Fix] 견적조회, 반려요청 페이지 반응형 레이아웃 개선

---

src/app/[locale]/(guest)/drivers/_components/FindDrivers.tsx
src/components/dropdown/FilterDropdown.tsx
src/components/dropdown/SortDropdown.tsx
src/components/input/SearchBar.tsx

- 테스트 중 Figma와 디자인 다른 부분이 있어 수정했습니다.
- `FindDrivers.tsx`
- SearchBar의 크기를 뷰포트 기준(`isLg`)으로 동적으로 적용
- 필터와 정렬 컴포넌트 레이아웃 개선
- `FilterDropdown.tsx`
- 버튼 높이/정렬 문제 해결
- 커서 포인터 추가
- `SortDropdown.tsx`
- 커서 포인터 추가
- 화살표 클릭 시 드롭다운 닫히지 않던 문제 해결 (`onClick` 토글로 수정)
- `SearchBar.tsx`
- 높이 사이즈 수정

[UI] 기사님찾기 페이지 검색/필터/정렬 UI 개선 및 버그 수정

---

src/app/[locale]/(protected)/driver/my-estimates/sent/[id]/_components/EstimateHeaderSection.tsx
src/app/[locale]/(protected)/driver/my-estimates/sent/[id]/page.tsx
src/messages/en/MyEstimate.json
src/messages/zh/MyEstimate.json

- 견적 조회 상세 페이지 반응형 수정
- 견적 정보 영역의 다국어 번역 오류 수정

[Fix] 견적 상세페이지 반응형 및 번역 오류 수정

---

src/app/[locale]/(guest)/drivers/_components/LikedDrivers.tsx
src/app/[locale]/(protected)/driver/my-page/page.tsx

1. 찜한 기사가 없을 때 찜한 기사님을 불러올 수 없다는 메시지가 뜨는 부분 수정했습니다.
2. 기사님 마이페이지에서 프로필 이미지가 있어도 기본이미지가 불려와지는 부분 수정했습니다. 

[FIX] favorite drivers

---

src/app/[locale]/(protected)/customer/my-estimates/estimate-past/[id]/PastDetail.tsx
src/app/[locale]/(protected)/customer/my-estimates/estimate-past/_components/ReceivedEstimate.tsx
src/app/[locale]/(protected)/customer/my-estimates/estimate-pending/[id]/PendingDetail.tsx
src/app/[locale]/(protected)/customer/my-estimates/estimate-pending/_components/PendingCard.tsx
src/app/[locale]/estimate/shared/[token]/page.tsx
src/components/Title.tsx
src/types/estimateType.ts

내 견적관리에서 좋아요 토글 버튼 기능 추가했습니다.
견적서 공유용 페이지 ui 조금 수정했습니다.

[김다은] 좋아요 토글 버튼 추가

---

src/app/[locale]/(guest)/drivers/[id]/_components/DesignatedEstimateButton.tsx

- 최대 3명 제한 에러메세지는 모달 말고 토스트로 뜨도록 수정했습니다.

feat: 최대 3명 제한 에러메세지 토스트로 뜨도록 수정

---

src/app/[locale]/(protected)/customer/my-estimates/estimate-pending/PendingEstimates.tsx
src/app/[locale]/estimate/shared/[token]/page.tsx

견적서 공유용 페이지에 견적서 공유하기 같이 넣었습니다.
대기중인 견적 페이지에서 렌더링 이상한 부분 수정했습니다. 

[김다은] 기능빠진 부분 수정

---

src/app/[locale]/(protected)/customer/my-estimates/estimate-pending/_components/PendingCard.tsx
src/app/[locale]/(protected)/driver/my-estimates/sent/[id]/_components/EstimateHeaderSection.tsx
src/app/[locale]/(protected)/driver/my-estimates/sent/[id]/_components/EstimateInfoSection.tsx
src/hooks/useFavoriteToggle.ts

[김다은] 시연 전 최종 수정..

---

src/app/[locale]/(protected)/customer/my-estimates/estimate-past/_components/ReceivedEstimate.tsx
src/app/[locale]/(protected)/customer/my-estimates/estimate-pending/[id]/PendingDetail.tsx

받았던 견적 하트 모양 조건 처리 & 견적 확정 모달 text 버그 수정
- 견적 확정 취소는 일단 우선순위 먼저 해결한 다음 생각해보겠습니다..
- 견적서 공유하기의 공유 버튼은 잘 안되고 있어서 나중에 해보고 해결이 안되면 넣지 않겠습니다.
- 그 이외의 기능 수정은 완료되었습니다. 

[김다은] 받았던 견적 하트 모양 조건 처리 & 견적 확정 모달 text 버그 수정

---

src/components/gnb/Gnb.tsx

- 브라우저를 리사이징 할 때 마다 gnb에서 불필요한 함수를 생성하고 있어서 리팩토링 진행했습니다.

[황수정] gnb 리팩토링

---

src/components/gnb/GnbListLayout.tsx
src/components/gnb/GnbMenuList.tsx

[황수정] gnb 메뉴 애니메이션 효과 적용

---

src/app/[locale]/(protected)/customer/estimate-request/DesktopEstimateForm.tsx
src/app/[locale]/(protected)/customer/estimate-request/DisabledForm.tsx
src/app/[locale]/(protected)/customer/estimate-request/MobileEstimateForm.tsx
src/app/[locale]/(protected)/customer/estimate-request/_components/card/AddressResultCard.tsx
src/app/[locale]/(protected)/customer/estimate-request/_components/card/MoveTypeCard.tsx
src/app/[locale]/(protected)/customer/estimate-request/_components/datepicker/DatePicker.tsx
src/app/[locale]/(protected)/customer/estimate-request/_components/datepicker/MobileDatePicker.tsx
src/app/[locale]/(protected)/customer/estimate-request/_components/dropdown/CalenderDropdown.tsx
src/app/[locale]/(protected)/customer/estimate-request/_components/modal/AddressCardModal.tsx
src/app/[locale]/(protected)/customer/estimate-request/_components/modal/DaumPostcodeModal.tsx

- 시맨틱 태그 적용했습니다.
- 웹 접근성 개선했습니다.
- alt 텍스트 추가
- aria 속성 불필요한 곳 제거, role 추가
- 불필요한 wrapper div 제거

[Refactor] 견적요청 페이지, 컴포넌트 UI 및 접근성 개선

---

src/app/[locale]/(protected)/customer/my-estimates/MyEstimate.tsx
src/app/[locale]/(protected)/customer/my-estimates/estimate-past/PastEstimates.tsx
src/app/[locale]/(protected)/customer/my-estimates/estimate-pending/PendingEstimates.tsx
src/app/[locale]/(protected)/customer/my-estimates/estimate-pending/[id]/PendingDetail.tsx

시맨틱 태그 적용 후 의도치 않게 바뀐 ui 다시 수정하였습니다..

[김다은] ui 수정

---

next.config.ts

백엔드에서 s3앞에 클라우드 프론트 추가 하고 프론트에서는 관련 설정 추가

[feat 이지수]:s3앞에 클라우드 프론트 추가

---

src/app/[locale]/(protected)/customer/my-estimates/estimate-pending/PendingEstimates.tsx
src/app/[locale]/estimate/shared/[token]/page.tsx

[김다은] ui 4차 수정

---

src/app/[locale]/(protected)/driver/my-estimates/sent/[id]/_components/EstimateHeaderSection.tsx
src/app/[locale]/(protected)/driver/my-estimates/sent/[id]/_components/EstimateInfoSection.tsx
src/app/[locale]/(protected)/driver/my-estimates/sent/[id]/page.tsx
src/app/[locale]/(protected)/driver/received-requests/page.tsx
src/components/ShareDriver.tsx

[Feat] 기사/견적 상세 페이지 성능 최적화

---

src/app/[locale]/(protected)/driver/my-estimates/sent/[id]/page.tsx
src/components/loading/LoadingAnimation.tsx

[Feat] 견적상세페이지 로딩수정

---

src/components/dropdown/ProfileDropdown.tsx
src/components/gnb/Gnb.tsx
src/components/gnb/GnbListLayout.tsx
src/components/gnb/GnbMenuList.tsx
src/components/gnb/_components/Logo.tsx
src/hooks/useGnbHook.ts
src/hooks/useTransitionRouter.ts

- gnb에서 해상도에 따라 프로필 레이어의 메뉴가 클릭되지 않는 이슈가 있음
- 리팩토링 후 발생한 버그로 원래의 코드로 롤백했음

[황수정] gnb/profileDropdown 롤백

---

src/app/[locale]/(protected)/customer/estimate-request/_components/modal/DaumPostcodeModal.tsx

fix: aria-label 오류 수정

---

src/app/[locale]/(protected)/customer/review/_components/ModalContent.tsx
src/app/[locale]/(protected)/customer/review/_components/ReviewsInner.tsx
src/app/[locale]/(protected)/customer/review/page.tsx
src/app/[locale]/(protected)/driver/my-estimates/sent/_components/CustomerEstimateCard.tsx
src/app/[locale]/(protected)/driver/received-requests/_components/ReceivedRequestCard.tsx

Locale:review received esti

---

package-lock.json
src/app/[locale]/(protected)/customer/review/_components/ModalContent.tsx
src/app/[locale]/(protected)/customer/review/_components/ReviewsInner.tsx
src/app/[locale]/(protected)/driver/my-estimates/sent/_components/CustomerEstimateCard.tsx
src/app/[locale]/(protected)/driver/received-requests/_components/ReceivedRequestCard.tsx

fix:deepL수정

---

src/app/[locale]/(protected)/driver/my-estimates/rejected/_components/CompletedRejectedCard.tsx
src/app/[locale]/(protected)/driver/my-estimates/rejected/page.tsx
src/app/[locale]/(protected)/driver/my-estimates/sent/_components/CustomerEstimateCard.tsx
src/app/[locale]/(protected)/driver/my-estimates/sent/page.tsx
src/app/[locale]/(protected)/driver/received-requests/_components/ReceivedRequestCard.tsx
src/app/[locale]/(protected)/driver/received-requests/page.tsx
src/utills/translateWithDeepL.ts

[fix] 동적다국어 백API 연결

---

src/app/[locale]/(protected)/customer/review/_components/DeleteConfirmModal.tsx
src/app/[locale]/(protected)/customer/review/_components/MyReviews.tsx
src/app/[locale]/(protected)/customer/review/_components/ReviewModal.tsx
src/app/[locale]/(protected)/customer/review/_components/ReviewsInner.tsx
src/app/[locale]/(protected)/customer/review/_components/WritableReviews.tsx

feat: review

---

src/app/[locale]/(protected)/driver/my-estimates/sent/_components/CustomerEstimateCard.tsx
src/hooks/useTranslate.ts

- 경로를 제대로 설정해주지 않아서 fetch 요청이 아예 안 갔던 문제 발견해서 일단 해결했습니다.

fix: 번역 요청 경로 오류 수정

---

src/app/[locale]/(protected)/customer/review/_components/ReviewsInner.tsx

fix: 다국어 요청 주소 수정
